### ISSUE TITLE
To-do's for 2023-03 Group Project

### ISSUE THREAD

**Issue by julietcohen** [NCEAS/scalable-computing-examples#3]
- [x] rename `.ipynb` docs to reflect 2023-03 schedule
- [x] debug pickling error
- [x] add comments to `.ipynb` docs 
- [x] edit intro text of group project, add content or links if desired (add viz of aggregating rasters to lower z-levels)
- [x] cite PDG packages and other packages used?
- [x] reduce size of input dataset
- [x] increase size of plotted tiles output
- [x] determine version of `viz-staging` / `viz-raster` to use, just SCC branch if works with current input data
- [x] review feedback from last year
- [x] modify helper functions 
- [x] change number of workers in parsl config to reflect new group size
- [x] run-through of all notebooks with SCC team concurrently
